# Database connection parameters
database:
  jdbcUrl: 'mysql://localhost:3306/authme'
  username: 'authme'
  password: '12345'
  tableName: 'authme'
  nameColumn: 'username'

# Player blacklist (useful for staff members, please use LOWERCASE names)
blacklist:
  - notch
  - steve

# Messages
messages:
  onlyPlayers: '&cThis command is available only to players!'
  protected: '&cThis account is protected, you can''t unregister it!'
  success: '&aYou have beed correcty unregistered from the database!'
  error: '&cAn error occurred while removing the user from the database.'
