# Database connection parameters
database:
  jdbcUrl: 'jdbc:mysql://localhost:3306/authme'
  username: 'authme'
  password: '12345'
  tableName: 'authme'
  nameColumn: 'username'
  passwordColumn: 'password'

unregister:
  enabled: true
  kick: true
  # Placeholders: %player%
  postCommands: []

changepassword:
  enabled: true
  kick: true
  # Placeholders: %player%
  postCommands: []

logFile: true

# Messages
messages:
  onlyPlayers: '&cThis command is available only to players!'
  protected: '&cThis account is protected, you can''t unregister it!'
  unregisterSuccess: '&aYou have been correcty unregistered from the database!'
  changepasswordSuccess: '&aYou have changed password correctly!'
  error: '&cAn error occurred while performing the command.'
